In [51]:
import pandas as pd
import openpyxl

In [52]:
cus = pd.read_excel('../dataset/Ecomm.xlsx',sheet_name='CustomerDetail')

In [53]:
ord = pd.read_excel('../dataset/Ecomm.xlsx',sheet_name='Jan')

In [54]:
cus = cus.drop(columns = ['CustomerID','Month','MonthName','DateInText','Gender','Gender.1'])

In [55]:
cus = cus.rename(columns ={'CustomerID.1':'Customer','Gender.2':'Gender'})
cus['Order Date']  = pd.to_datetime(cus['Order Date'])

In [56]:
cus.shape

(24, 6)

In [57]:
cus.head(3)

   Customer Order Date   Customer Name State or Province         City  Gender
0      7253 2015-01-07   Bonnie Potter        Washington    Anacortes    MALE
1      4875 2015-06-13  Ronnie Proctor        California  San Gabriel  FEMALE
2      2748 2015-02-15   Marcus Dunlap        New Jersey      Roselle    MALE

In [58]:
cus.isnull().sum().sum()

np.int64(0)

In [59]:
ord.head(3)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card
2,90192,2583,208.56,-53.8096,22,Furniture,Office Furnishings,Credit Card

In [60]:
ord = ord.rename( columns = {'Quantity ordered new':'Quantity'})

In [61]:
ord.shape

(1952, 8)

In [62]:
cus.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer           24 non-null     int64
 1   Order Date         24 non-null     datetime64[us]
 2   Customer Name      24 non-null     str
 3   State or Province  24 non-null     str
 4   City               24 non-null     str
 5   Gender             24 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 2.1 KB

In [63]:
ord.info()

<class 'pandas.DataFrame'>
RangeIndex: 1952 entries, 0 to 1951
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              1952 non-null   int64
 1   CustomerID            1952 non-null   int64
 2   Amount                1952 non-null   float64
 3   Profit                1952 non-null   float64
 4   Quantity              1952 non-null   int64
 5   Product Category      1952 non-null   str
 6   Product Sub-Category  1952 non-null   str
 7   Payment Mode          1952 non-null   str
dtypes: float64(2), int64(3), str(3)
memory usage: 199.4 KB

In [64]:
for i in range(0,cus.shape[0]):
    print(cus.loc[i])

Customer                            7253
Order Date           2015-01-07 00:00:00
Customer Name              Bonnie Potter
State or Province             Washington
City                           Anacortes
Gender                              MALE
Name: 0, dtype: object
Customer                            4875
Order Date           2015-06-13 00:00:00
Customer Name             Ronnie Proctor
State or Province             California
City                         San Gabriel
Gender                            FEMALE
Name: 1, dtype: object
Customer                            2748
Order Date           2015-02-15 00:00:00
Customer Name              Marcus Dunlap
State or Province             New Jersey
City                             Roselle
Gender                              MALE
Name: 2, dtype: object
Customer                            4565
Order Date           2015-05-12 00:00:00
Customer Name          Gwendolyn F Tyson
State or Province              Minnesota
City                          Prior Lake
Gender                              MALE
Name: 3, dtype: object
Customer                            4666
Order Date           2015-05-12 00:00:00
Customer Name          Gwendolyn F Tyson
State or Province              Minnesota
City                          Prior Lake
Gender                              MALE
Name: 4, dtype: object
Customer                            4663
Order Date           2015-05-12 00:00:00
Customer Name          Gwendolyn F Tyson
State or Province              Minnesota
City                          Prior Lake
Gender                            FEMALE
Name: 5, dtype: object
Customer                            2583
Order Date           2015-05-12 00:00:00
Customer Name          Gwendolyn F Tyson
State or Province              Minnesota
City                          Prior Lake
Gender                              MALE
Name: 6, dtype: object
Customer                            8372
Order Date           2015-04-08 00:00:00
Customer Name              Timothy Reese
State or Province               New York
City                           Smithtown
Gender                              MALE
Name: 7, dtype: object
Customer                            6458
Order Date           2015-05-28 00:00:00
Customer Name              Timothy Reese
State or Province               New York
City                           Smithtown
Gender                              MALE
Name: 8, dtype: object
Customer                            2834
Order Date           2015-02-12 00:00:00
Customer Name               Sarah Ramsey
State or Province               New York
City                            Syracuse
Gender                            FEMALE
Name: 9, dtype: object
Customer                            8264
Order Date           2015-02-12 00:00:00
Customer Name               Sarah Ramsey
State or Province               New York
City                            Syracuse
Gender                              MALE
Name: 10, dtype: object
Customer                            8363
Order Date           2015-05-15 00:00:00
Customer Name               Laurie Hanna
State or Province                Montana
City                              Helena
Gender                              MALE
Name: 11, dtype: object
Customer                            4556
Order Date           2015-05-21 00:00:00
Customer Name                Jim Rodgers
State or Province                Montana
City                            Missoula
Gender                              MALE
Name: 12, dtype: object
Customer                             5243
Order Date            2015-05-15 00:00:00
Customer Name        Tony Wilkins Winters
State or Province                New York
City                        New York City
Gender                             FEMALE
Name: 13, dtype: object
Customer                             5654
Order Date            2015-05-21 00:00:00
Customer Name        Tony Wilkins Winters
State or Province                New York
City                        New York City
Gender                               MALE
Name: 14, dtype: object
Customer                             2357
Order Date            2015-05-21 00:00:00
Customer Name        Tony Wilkins Winters
State or Province                New York
City                        New York City
Gender                               MALE
Name: 15, dtype: object
Customer                            7876
Order Date           2015-01-28 00:00:00
Customer Name                Edna Thomas
State or Province             California
City                       Laguna Niguel
Gender                              MALE
Name: 16, dtype: object
Customer                            5265
Order Date           2015-01-28 00:00:00
Customer Name                Edna Thomas
State or Province             California
City                       Laguna Niguel
Gender                            FEMALE
Name: 17, dtype: object
Customer                            1573
Order Date           2015-05-02 00:00:00
Customer Name              Guy Gallagher
State or Province             California
City                            Lakewood
Gender                              MALE
Name: 18, dtype: object
Customer                            7356
Order Date           2015-02-22 00:00:00
Customer Name             Matthew Berman
State or Province                 Oregon
City                         Grants Pass
Gender                              MALE
Name: 19, dtype: object
Customer                            3445
Order Date           2015-03-27 00:00:00
Customer Name             Matthew Berman
State or Province                 Oregon
City                         Grants Pass
Gender                              MALE
Name: 20, dtype: object
Customer                            6735
Order Date           2015-01-20 00:00:00
Customer Name             Matthew Berman
State or Province                 Oregon
City                         Grants Pass
Gender                            FEMALE
Name: 21, dtype: object
Customer                            8845
Order Date           2015-03-12 00:00:00
Customer Name             Matthew Berman
State or Province                 Oregon
City                         Grants Pass
Gender                              MALE
Name: 22, dtype: object
Customer                            4568
Order Date           2015-06-15 00:00:00
Customer Name              Ricky Hensley
State or Province                 Oregon
City                             Gresham
Gender                              MALE
Name: 23, dtype: object

In [65]:
cus = pd.read_csv("../dataset/customer.csv")
ord = pd.read_csv("../dataset/orders.csv")

In [69]:
df = pd.merge(ord,cus,on='CustomerID', how='inner')

In [71]:
df

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode,Order Date,Customer Name,State or Province,City,Gender
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,FEMALE
2,90192,2583,208.56,-53.8096,22,Furniture,Office Furnishings,Credit Card,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE
3,86838,8372,1259.04,803.4705,16,Furniture,Office Furnishings,Credit Card,2015-04-08,Timothy Reese,New York,Smithtown,MALE
4,86838,6458,22.96,-24.0300,7,Office Supplies,Pens & Art Supplies,Credit Card,2015-05-28,Timothy Reese,New York,Smithtown,MALE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1947,87536,2357,196.20,-116.7600,18,Office Supplies,Storage & Organization,Credit Card,2015-05-21,Tony Wilkins Winters,New York,New York City,MALE
1948,87536,7876,175.78,-160.9520,22,Technology,Telephones and Communication,Credit Card,2015-01-28,Edna Thomas,California,Laguna Niguel,MALE
1949,87534,5265,59.85,-41.8700,5,Office Supplies,Pens & Art Supplies,Credit Card,2015-01-28,Edna Thomas,California,Laguna Niguel,FEMALE
1950,87537,1573,140.70,-24.7104,15,Furniture,Office Furnishings,Credit Card,2015-05-02,Guy Gallagher,California,Lakewood,MALE
1951,87530,4666,529.90,349.4850,5,Furniture,Office Furnishings,Credit Card,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE

In [70]:
import streamlit as st