In [7]:
import pandas as pd
import openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [22]:
cus = pd.read_excel('../dataset/Ecomm.xlsx',sheet_name='CustomerDetail')

In [9]:
ord = pd.read_excel('../dataset/Ecomm.xlsx',sheet_name='Jan')

In [23]:
cus.shape

(24, 12)

In [27]:
cus.head(3)

,CustomerID.1,Order Date,MonthName,Customer Name,State or Province,City,Gender.2
0,7253,2015-01-07,Jan,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Jun,Ronnie Proctor,California,San Gabriel,FEMALE
2,2748,2015-02-15,Feb,Marcus Dunlap,New Jersey,Roselle,MALE

In [30]:
cus.isnull().sum().sum()

np.int64(0)

In [29]:
cus = cus.rename(columns ={'CustomerID.1':'Customer','Gender.2':'Gender'})

In [ ]:
cus = cus.drop(columns=['CustomerID','Month','DateInText','Gender.1','Gender']  )

In [35]:
ord.head(3)

,Order ID,CustomerID,Amount,Profit,Quantity,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card
2,90192,2583,208.56,-53.8096,22,Furniture,Office Furnishings,Credit Card

In [34]:
ord = ord.rename( columns = {'Quantity ordered new':'Quantity'})

In [20]:
ord.shape

(1952, 8)